### ISSUE TITLE
How can I specify a relative URL for a raw XML file?

### ISSUE THREAD

**Issue by JackStoneDev** [signmeup/accounts-saml2#15]
My metadata file is `metadata.xml`, which is housed on the same directory level as `settings.json`. How can I specify a relative URL to this file for `metadataUrl`?

**Comment by athyuttamre** [comment]
Apologies for the late response -- unfortunately we don't support this at the moment, but feel free to write a script that sets the `METEOR_SETTINGS` environment variable when running your meteor setup. This way you can read from `metadata.xml` and update your settings at runtime.

Last I looked at reading files from Atmosphere packages (which was two years ago, so my knowledge is outdated), it was really hard to access them. I've noted this in the README:

>Unfortunately, there isn't a clean way to read files from within a Package. Options include using Node's fs, or the app reading the file and passing to the package. The Assets API isn't available i.e. packages can't read user assets. For more discussion, see this issue. For a hacky fix, see this piece of code.

If you find a way though, please post here and I'll gladly discuss and help you implement it. This is where the metadata is extracted in the code: https://github.com/signmeup/accounts-saml2/blob/master/server/saml_server.js#L12.

**Comment by JackStoneDev** [comment]
How would that script input the metadata though? Wouldn't it still have to be a URL?

**Comment by athyuttamre** [comment]
The script can be a JavaScript script called `run-meteor.js` for example. When executed, it would read `metadata.xml` from disk, parse that to an object; then it would read `settings.json` from disk, parse that to an object. And finally it would set the environment variable `METEOR_SETTINGS`, and then run the Meteor app.

We're basically running a Meteor app that reads its settings from an environment variable, and modifying that environment variable to suit our needs. Does that help?

**Comment by JackStoneDev** [comment]
Right, makes sense, but the `metadataUrl` parameter only takes a URL as per the package documentation. How could I stick an object in there?

**Comment by athyuttamre** [comment]
I'm sorry again for the late response. I think I might be misunderstanding what you're asking for. The `metadataUrl` is actually a URL you hit to _get_ the metadata file i.e. accessing that URL will generate a file that you can download.

**Comment by JackStoneDev** [comment]
Right. Could I specify an xml file in that `metadataUrl` parameter though? The documentation seems to suggest that I cannot.

**Comment by athyuttamre** [comment]
I’m sorry, what is in your XML file? The metadataUrl specifies a route that
you can hit to download the metadata associated with your service. It’s not
something you upload a file to.

**Comment by JackStoneDev** [comment]
And so this is a Meteor route? I'm still a little confused.

**Comment by athyuttamre** [comment]
It's a route exposed by the package on your Meteor app. So you would navigate to `https://your-site.com/<metadataUrl>` to download the metadata file which then you would provide to your SAML provider. An example file can be found at `https://signmeup.cs.brown.edu/saml/metadata`.

Could you perhaps explain what you're trying to build, where you got the file from, and why you want to pass it to the `metadataUrl`?

**Comment by JackStoneDev** [comment]
I am implementing SAML login for a large institution with a metadata file.

**Comment by athyuttamre** [comment]
@JackStoneDev I'm sorry I haven't been able to help you directly; mostly because it appears the use of `metadataUrl` hasn't been clear to you.

If you still need this package to work, I'm happy to get on a short call to discuss this briefly. If interested, please email me directly at the email on my profile. I'm going to close this issue in the meantime since there isn't a direct action for me. Thanks!
